version: "3.1"

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_HOST=2024-quaint-db.mysql.database.azure.com
      - PMA_USER=seigo
      - PMA_PASSWORD=Aozora0719_d
